# See: https://taskfile.dev/api/

version: "3"

tasks:
  run-local:
    aliases:
      - local
    desc: "Run app local"
    cmds:
      - go run cmd/content/main.go --config="./config/local.yaml"

  migrate:
    desc: "Apply migrations (before use, make folder in root)"
    cmds:
      - mkdir -p storage/
      - go run cmd/migrator/main.go --storage-path="./storage/content.db" --migrations-path="./migrations"
