env: "local"
storage_path: "./storage/content.db"
grpc:
  port: 44045
  timeout: 10h
  gateway_port: 8082
token: "TEST"
clients:
  auth:
    address: "localhost:44044"
    timeout: 60s
    retriesCount: 10